blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/craftcms/console/discussions/new?category=craft-console
    about: Start a new discussion about your idea
